[package]
name = "sql_wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.7.4", features = ["runtime-tokio", "postgres", "chrono", "sqlx-postgres", "uuid", "rust_decimal"] }
sql-builder = "3.1.1"
tokio = { version = "1.38.0", features = ["macros"] }
chrono = "0.4.38"
bigdecimal = "0.4"
serde_json = "1.0"
uuid = { version = "1.8.0", features = ["v4"] }